# Generated by ./install.sh — do not edit by hand; re-run the installer.
tap "FelixKratz/formulae", trusted: {
  formulae: ["sketchybar", "borders"],
}
tap "koekeishiya/formulae", trusted: {
  formulae: ["skhd"],
}

brew "stow"
brew "gum"
brew "jq"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-completions"
brew "bat"
brew "btop"
brew "duti"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "ncdu"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tldr"
brew "uv"
brew "zoxide"
brew "yazi"
brew "FelixKratz/formulae/sketchybar", trusted: true
brew "blueutil"
brew "FelixKratz/formulae/borders", trusted: true
brew "koekeishiya/formulae/skhd", trusted: true

cask "ghostty"
cask "omniwm"
cask "cursor"
cask "sublime-text"
cask "teamviewer"
cask "transmission"
cask "iina"
cask "libreoffice"
cask "nvidia-geforce-now"
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-symbols-only-nerd-font"
cask "font-sketchybar-app-font"
