#!/usr/bin/env zsh
# Generate app theme files from palette tokens + templates.
# Usage: apply.sh apply <palette> | list | current
set -euo pipefail

SCRIPT_DIR="${0:A:h}"
THEME_DIR="${SCRIPT_DIR}"
TEMPLATES_DIR="${THEME_DIR}/templates"
PALETTES_DIR="${THEME_DIR}/palettes"
ACTIVE_FILE="${HOME}/.config/theme/active"

# Token names substituted as {{NAME}} in templates.
typeset -a THEME_TOKENS=(
  THEME_NAME
  BASE SURFACE SURFACE_ALT THEME_BORDER FG MUTED
  BLUE BLUE_BRIGHT PURPLE AMBER
  RED GREEN YELLOW CYAN MAGENTA BLUE_ANSI
  PURPLE_RGB_CSV MUTED_RGB_CSV BLUE_BRIGHT_RGB_CSV
)

theme_die() {
  print -u2 -- "theme: $*"
  exit 1
}

theme_info() {
  print -r -- "theme: $*"
}

theme_list() {
  local d
  for d in "${PALETTES_DIR}"/*(N/); do
    print -r -- "${d:t}"
  done
}

theme_current() {
  if [[ -f "${ACTIVE_FILE}" ]]; then
    print -r -- "$(<"${ACTIVE_FILE}")"
  else
    print -r -- "cinematic-noir"
  fi
}

theme_rgb_csv() {
  local hex="${1#\#}"
  printf '%d,%d,%d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# Replace leftover stow symlinks with a real file write.
theme_write() {
  local dest="$1"
  local content="$2"
  mkdir -p "${dest:h}"
  if [[ -L "${dest}" ]]; then
    rm -f "${dest}"
  fi
  print -r -- "${content}" >"${dest}"
}

theme_render() {
  local src="$1"
  local content var val
  content="$(<"${src}")"
  for var in "${THEME_TOKENS[@]}"; do
    val="${(P)var}"
    content="${content//\{\{$var\}\}/${val}}"
  done
  if [[ "${content}" == *'{{'* ]]; then
    local leftover
    leftover="$(print -r -- "${content}" | grep -oE '\{\{[A-Z0-9_]+\}\}' | sort -u | tr '\n' ' ')"
    if [[ -n "${leftover// }" ]]; then
      theme_die "unsubstituted tokens in ${src:t}: ${leftover}"
    fi
  fi
  print -r -- "${content}"
}

theme_emit_colors_env() {
  local out
  out="# Generated by theme apply — do not edit; change palettes/${THEME_NAME}/colors.sh
THEME_NAME=${THEME_NAME}
BASE=${BASE}
SURFACE=${SURFACE}
SURFACE_ALT=${SURFACE_ALT}
THEME_BORDER=${THEME_BORDER}
FG=${FG}
MUTED=${MUTED}
BLUE=${BLUE}
BLUE_BRIGHT=${BLUE_BRIGHT}
PURPLE=${PURPLE}
AMBER=${AMBER}
RED=${RED}
GREEN=${GREEN}
YELLOW=${YELLOW}
CYAN=${CYAN}
MAGENTA=${MAGENTA}
BLUE_ANSI=${BLUE_ANSI}
"
  theme_write "${HOME}/.config/theme/colors.env" "${out}"
}

theme_set_wallpaper() {
  local name="$1"
  local src=""
  local candidate
  for candidate in \
    "${PALETTES_DIR}/${name}/wallpaper.png" \
    "${PALETTES_DIR}/${name}/wallpaper.jpg" \
    "${PALETTES_DIR}/${name}/wallpaper.jpeg"
  do
    if [[ -f "${candidate}" ]]; then
      src="${candidate}"
      break
    fi
  done
  [[ -n "${src}" ]] || return 0

  local dest_dir="${HOME}/.config/wallpaper"
  local dest="${dest_dir}/current.png"
  mkdir -p "${dest_dir}"
  cp -f "${src}" "${dest}"

  if /usr/bin/osascript <<EOF
set img to POSIX file "${dest}"
tell application "System Events"
  repeat with d in (a reference to every desktop)
    try
      set picture of d to img
    end try
  end repeat
end tell
EOF
  then
    theme_info "wallpaper → ${dest}"
  else
    theme_info "wallpaper copied but System Events set failed"
  fi
}

# Invoke a rice app's --reload via PATH, else ~/Applications (or /Applications).
theme_reload_app() {
  local cmd="$1"
  local app_name="$2"
  if (( $+commands[$cmd] )); then
    "$cmd" --reload 2>/dev/null && return 0
  fi
  local bin
  for bin in \
    "${HOME}/Applications/${app_name}.app/Contents/MacOS/${app_name}" \
    "/Applications/${app_name}.app/Contents/MacOS/${app_name}"
  do
    if [[ -x "${bin}" ]]; then
      "${bin}" --reload 2>/dev/null || true
      return 0
    fi
  done
  return 1
}

theme_reload_omniwm() {
  local label="com.dotfiles.omniwm"
  local domain="gui/$(id -u)/${label}"
  if launchctl print "${domain}" &>/dev/null; then
    launchctl kickstart -k "${domain}" 2>/dev/null && return 0
  fi
  if [[ -d "/Applications/OmniWM.app" ]]; then
    open -a OmniWM 2>/dev/null || true
    return 0
  fi
  return 1
}

# Materialize ~/.config/omniwm/settings.toml if it is still a stow symlink, then
# rewrite OmniWM color tables from the active palette (BLUE_BRIGHT / AMBER / …).
theme_patch_omniwm_colors() {
  local dest="${HOME}/.config/omniwm/settings.toml"
  mkdir -p "${dest:h}"

  if [[ -L "${dest}" ]]; then
    local tmp
    tmp="$(mktemp)"
    cp -f "${dest}" "${tmp}"
    rm -f "${dest}"
    mv "${tmp}" "${dest}"
    theme_info "materialized ${dest} (was stow symlink; colors now theme-owned)"
  fi

  if [[ ! -f "${dest}" ]]; then
    local pkg="${THEME_DIR:A:h:h}/omniwm/.config/omniwm/settings.toml"
    if [[ -f "${pkg}" ]]; then
      cp -f "${pkg}" "${dest}"
      theme_info "seeded ${dest} from package defaults"
    else
      theme_info "skip OmniWM colors — no settings.toml at ${dest}"
      return 0
    fi
  fi

  local patcher="${THEME_DIR}/patch_omniwm_colors.py"
  [[ -f "${patcher}" ]] || theme_die "missing ${patcher}"
  # Env already holds BASE / BLUE_BRIGHT / AMBER / THEME_BORDER from the palette.
  /usr/bin/env python3 "${patcher}" "${dest}"
}

# Resolve Zen Browser profile directories (macOS Application Support).
theme_zen_profiles() {
  local support="${HOME}/Library/Application Support/zen"
  local profiles_ini="${support}/profiles.ini"
  [[ -d "${support}" ]] || return 1

  local -a paths=()
  local line rel path
  if [[ -f "${profiles_ini}" ]]; then
    while IFS= read -r line || [[ -n "${line}" ]]; do
      [[ "${line}" == Path=* ]] || continue
      rel="${line#Path=}"
      if [[ "${rel}" == /* ]]; then
        path="${rel}"
      else
        path="${support}/${rel}"
      fi
      [[ -d "${path}" ]] && paths+=("${path}")
    done <"${profiles_ini}"
  fi

  if (( ${#paths[@]} == 0 )); then
    for path in "${support}/Profiles"/*(N/); do
      [[ -f "${path}/prefs.js" ]] && paths+=("${path}")
    done
  fi

  (( ${#paths[@]} > 0 )) || return 1
  print -l -- "${paths[@]}"
}

# Ensure userChrome.css is honored (read from user.js on next Zen start).
theme_ensure_zen_userjs() {
  local dest="$1/user.js"
  local pref='user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'
  local begin="// BEGIN dotfiles-theme"
  local end="// END dotfiles-theme"
  local block="${begin}
${pref}
${end}"

  if [[ -f "${dest}" ]]; then
    local content
    content="$(<"${dest}")"
    # Strip a previous managed block, then any stray copies of the pref line.
    content="$(print -r -- "${content}" | awk -v b="${begin}" -v e="${end}" '
      $0 == b { skip=1; next }
      $0 == e { skip=0; next }
      skip { next }
      /toolkit\.legacyUserProfileCustomizations\.stylesheets/ { next }
      { print }
    ')"
    content="${content%%$'\n'}"
    if [[ -n "${content}" ]]; then
      theme_write "${dest}" "${content}"$'\n\n'"${block}"
    else
      theme_write "${dest}" "${block}"
    fi
  else
    theme_write "${dest}" "${block}"
  fi
}

# Install/update the local Dotfiles Cursor theme extension + pin settings.
theme_apply_cursor() {
  local cursor_app="/Applications/Cursor.app"
  local ext_root="${HOME}/.cursor/extensions"
  local settings="${HOME}/Library/Application Support/Cursor/User/settings.json"

  # Skip quietly when Cursor is not installed (optional brew cask).
  if [[ ! -d "${cursor_app}" ]] && [[ ! -d "${ext_root}" ]] && [[ ! -f "${settings}" ]]; then
    theme_info "skip Cursor — not installed"
    return 0
  fi

  local theme_tmpl="${TEMPLATES_DIR}/cursor-color-theme.json"
  local pkg_tmpl="${TEMPLATES_DIR}/cursor-theme-package.json"
  [[ -f "${theme_tmpl}" ]] || theme_die "missing template: cursor-color-theme.json"
  [[ -f "${pkg_tmpl}" ]] || theme_die "missing template: cursor-theme-package.json"

  local ext_dir="${ext_root}/dotfiles.theme-0.0.1"
  mkdir -p "${ext_dir}/themes"

  local rendered_theme rendered_pkg
  rendered_theme="$(theme_render "${theme_tmpl}")"
  rendered_pkg="$(theme_render "${pkg_tmpl}")"
  theme_write "${ext_dir}/themes/Dotfiles-color-theme.json" "${rendered_theme}"
  theme_write "${ext_dir}/package.json" "${rendered_pkg}"
  theme_info "wrote Cursor theme → ${ext_dir}"

  local patcher="${THEME_DIR}/patch_cursor_theme.py"
  [[ -f "${patcher}" ]] || theme_die "missing ${patcher}"
  /usr/bin/env python3 "${patcher}" "${ext_root}" "${settings}"
  theme_info "Cursor: reload window (Cmd+Shift+P → Developer: Reload Window) to pick up Dotfiles"
}

# Write palette-driven userChrome/userContent into every Zen profile.
theme_apply_zen() {
  local -a profiles
  profiles=("${(@f)$(theme_zen_profiles 2>/dev/null || true)}")
  if (( ${#profiles[@]} == 0 )); then
    theme_info "skip Zen — no profile under ~/Library/Application Support/zen"
    return 0
  fi

  local chrome_tmpl="${TEMPLATES_DIR}/zen.userChrome.css"
  local content_tmpl="${TEMPLATES_DIR}/zen.userContent.css"
  [[ -f "${chrome_tmpl}" ]] || theme_die "missing template: zen.userChrome.css"
  [[ -f "${content_tmpl}" ]] || theme_die "missing template: zen.userContent.css"

  local chrome_rendered content_rendered profile
  chrome_rendered="$(theme_render "${chrome_tmpl}")"
  content_rendered="$(theme_render "${content_tmpl}")"

  for profile in "${profiles[@]}"; do
    mkdir -p "${profile}/chrome"
    theme_write "${profile}/chrome/userChrome.css" "${chrome_rendered}"
    theme_write "${profile}/chrome/userContent.css" "${content_rendered}"
    theme_ensure_zen_userjs "${profile}"
    theme_info "wrote Zen chrome → ${profile}/chrome/"
  done
  theme_info "Zen: restart the browser (or Style Editor reload) to pick up CSS"
}

theme_reload() {
  theme_reload_omniwm || true
  theme_reload_app launcher Launcher || true
  theme_reload_app calendar-bar CalendarBar || true
  theme_reload_app bar Bar || true
  if (( $+commands[bat] )); then
    bat cache --build 2>/dev/null || true
  fi
}

theme_apply() {
  local name="${1:-}"
  [[ -n "${name}" ]] || theme_die "usage: theme apply <palette>"
  local palette="${PALETTES_DIR}/${name}/colors.sh"
  [[ -f "${palette}" ]] || theme_die "unknown palette '${name}' (see: theme list)"

  mkdir -p "${HOME}/.config/theme"
  print -r -- "${name}" >"${ACTIVE_FILE}"

  # shellcheck source=/dev/null
  source "${palette}"
  export PURPLE_RGB_CSV="$(theme_rgb_csv "$PURPLE")"
  export MUTED_RGB_CSV="$(theme_rgb_csv "$MUTED")"
  export BLUE_BRIGHT_RGB_CSV="$(theme_rgb_csv "$BLUE_BRIGHT")"

  local -A outs=(
    [ghostty.theme]="${HOME}/.config/ghostty/themes/active"
    [btop.theme]="${HOME}/.config/btop/themes/active.theme"
    [bat.tmTheme]="${HOME}/.config/bat/themes/Dotfiles.tmTheme"
    [nvim.lua]="${HOME}/.config/nvim/colors/active.lua"
    [yazi.theme.toml]="${HOME}/.config/yazi/theme.toml"
    [starship.toml]="${HOME}/.config/starship.toml"
    [sublime.sublime-color-scheme]="${HOME}/Library/Application Support/Sublime Text/Packages/User/Dotfiles.sublime-color-scheme"
    [ripgrep.config]="${HOME}/.config/ripgrep/config"
    [git-colors.gitconfig]="${HOME}/.config/git/theme.gitconfig"
    [launcher.config.json]="${HOME}/.config/launcher/config.json"
    [calendar.config.json]="${HOME}/.config/calendar/config.json"
    [bar.config.json]="${HOME}/.config/bar/config.json"
  )

  local tmpl dest rendered
  for tmpl dest in ${(kv)outs}; do
    [[ -f "${TEMPLATES_DIR}/${tmpl}" ]] || theme_die "missing template: ${tmpl}"
    rendered="$(theme_render "${TEMPLATES_DIR}/${tmpl}")"
    theme_write "${dest}" "${rendered}"
    theme_info "wrote ${dest}"
  done

  theme_emit_colors_env
  theme_info "wrote ${HOME}/.config/theme/colors.env"

  # OmniWM settings.toml color tables (borders / overview / workspaceBar).
  theme_patch_omniwm_colors

  # Zen Browser userChrome / userContent (profile chrome/).
  theme_apply_zen

  # Cursor local theme extension + settings pin (Dotfiles).
  theme_apply_cursor

  theme_info "active → ${name}"

  theme_set_wallpaper "${name}"
  theme_reload
  theme_info "reload hooks finished (new shells pick up cli.sh; Ghostty/Zen/Cursor may need a reload)"
}

cmd="${1:-}"
case "${cmd}" in
  apply)
    shift
    theme_apply "${1:-}"
    ;;
  list)
    theme_list
    ;;
  current)
    theme_current
    ;;
  ""|-h|--help|help)
    print -r -- "usage: theme apply <palette> | theme list | theme current"
    ;;
  *)
    theme_die "unknown command '${cmd}' (apply|list|current)"
    ;;
esac
