#!/usr/bin/env zsh
# Generate app theme files from palette tokens + templates.
# Usage: apply.sh apply <palette> | list | current
set -euo pipefail

SCRIPT_DIR="${0:A:h}"
THEME_DIR="${SCRIPT_DIR}"
TEMPLATES_DIR="${THEME_DIR}/templates"
PALETTES_DIR="${THEME_DIR}/palettes"
ACTIVE_FILE="${HOME}/.config/theme/active"

# Token names substituted as {{NAME}} in templates.
typeset -a THEME_TOKENS=(
  THEME_NAME
  BASE SURFACE SURFACE_ALT THEME_BORDER FG MUTED
  BLUE BLUE_BRIGHT PURPLE AMBER
  RED GREEN YELLOW CYAN MAGENTA BLUE_ANSI
  PURPLE_RGB_CSV MUTED_RGB_CSV BLUE_BRIGHT_RGB_CSV
)

theme_die() {
  print -u2 -- "theme: $*"
  exit 1
}

theme_info() {
  print -r -- "theme: $*"
}

theme_list() {
  local d
  for d in "${PALETTES_DIR}"/*(N/); do
    print -r -- "${d:t}"
  done
}

theme_current() {
  if [[ -f "${ACTIVE_FILE}" ]]; then
    print -r -- "$(<"${ACTIVE_FILE}")"
  else
    print -r -- "cinematic-noir"
  fi
}

theme_rgb_csv() {
  local hex="${1#\#}"
  printf '%d,%d,%d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# Replace leftover stow symlinks with a real file write.
theme_write() {
  local dest="$1"
  local content="$2"
  mkdir -p "${dest:h}"
  if [[ -L "${dest}" ]]; then
    rm -f "${dest}"
  fi
  print -r -- "${content}" >"${dest}"
}

theme_render() {
  local src="$1"
  local content var val
  content="$(<"${src}")"
  for var in "${THEME_TOKENS[@]}"; do
    val="${(P)var}"
    content="${content//\{\{$var\}\}/${val}}"
  done
  if [[ "${content}" == *'{{'* ]]; then
    local leftover
    leftover="$(print -r -- "${content}" | grep -oE '\{\{[A-Z0-9_]+\}\}' | sort -u | tr '\n' ' ')"
    if [[ -n "${leftover// }" ]]; then
      theme_die "unsubstituted tokens in ${src:t}: ${leftover}"
    fi
  fi
  print -r -- "${content}"
}

theme_emit_colors_env() {
  local out
  out="# Generated by theme apply — do not edit; change palettes/${THEME_NAME}/colors.sh
THEME_NAME=${THEME_NAME}
BASE=${BASE}
SURFACE=${SURFACE}
SURFACE_ALT=${SURFACE_ALT}
THEME_BORDER=${THEME_BORDER}
FG=${FG}
MUTED=${MUTED}
BLUE=${BLUE}
BLUE_BRIGHT=${BLUE_BRIGHT}
PURPLE=${PURPLE}
AMBER=${AMBER}
RED=${RED}
GREEN=${GREEN}
YELLOW=${YELLOW}
CYAN=${CYAN}
MAGENTA=${MAGENTA}
BLUE_ANSI=${BLUE_ANSI}
"
  theme_write "${HOME}/.config/theme/colors.env" "${out}"
}

theme_set_wallpaper() {
  local name="$1"
  local src=""
  local candidate
  for candidate in \
    "${PALETTES_DIR}/${name}/wallpaper.png" \
    "${PALETTES_DIR}/${name}/wallpaper.jpg" \
    "${PALETTES_DIR}/${name}/wallpaper.jpeg"
  do
    if [[ -f "${candidate}" ]]; then
      src="${candidate}"
      break
    fi
  done
  [[ -n "${src}" ]] || return 0

  local dest_dir="${HOME}/.config/wallpaper"
  local dest="${dest_dir}/current.png"
  mkdir -p "${dest_dir}"
  cp -f "${src}" "${dest}"

  if /usr/bin/osascript <<EOF
set img to POSIX file "${dest}"
tell application "System Events"
  repeat with d in (a reference to every desktop)
    try
      set picture of d to img
    end try
  end repeat
end tell
EOF
  then
    theme_info "wallpaper → ${dest}"
  else
    theme_info "wallpaper copied but System Events set failed"
  fi
}

theme_reload() {
  if (( $+commands[sketchybar] )); then
    sketchybar --reload 2>/dev/null || true
  fi
  if (( $+commands[brew] )) && brew services list 2>/dev/null | grep -q '^borders '; then
    brew services restart borders 2>/dev/null || true
  fi
  if (( $+commands[launcher] )); then
    launcher --reload 2>/dev/null || true
  fi
  if (( $+commands[calendar-bar] )); then
    calendar-bar --reload 2>/dev/null || true
  fi
  if (( $+commands[bat] )); then
    bat cache --build 2>/dev/null || true
  fi
}

theme_apply() {
  local name="${1:-}"
  [[ -n "${name}" ]] || theme_die "usage: theme apply <palette>"
  local palette="${PALETTES_DIR}/${name}/colors.sh"
  [[ -f "${palette}" ]] || theme_die "unknown palette '${name}' (see: theme list)"

  mkdir -p "${HOME}/.config/theme"
  print -r -- "${name}" >"${ACTIVE_FILE}"

  # shellcheck source=/dev/null
  source "${palette}"
  export PURPLE_RGB_CSV="$(theme_rgb_csv "$PURPLE")"
  export MUTED_RGB_CSV="$(theme_rgb_csv "$MUTED")"
  export BLUE_BRIGHT_RGB_CSV="$(theme_rgb_csv "$BLUE_BRIGHT")"

  local -A outs=(
    [ghostty.theme]="${HOME}/.config/ghostty/themes/active"
    [btop.theme]="${HOME}/.config/btop/themes/active.theme"
    [bat.tmTheme]="${HOME}/.config/bat/themes/Dotfiles.tmTheme"
    [nvim.lua]="${HOME}/.config/nvim/colors/active.lua"
    [yazi.theme.toml]="${HOME}/.config/yazi/theme.toml"
    [starship.toml]="${HOME}/.config/starship.toml"
    [sublime.sublime-color-scheme]="${HOME}/Library/Application Support/Sublime Text/Packages/User/Dotfiles.sublime-color-scheme"
    [ripgrep.config]="${HOME}/.config/ripgrep/config"
    [git-colors.gitconfig]="${HOME}/.config/git/theme.gitconfig"
    [launcher.config.json]="${HOME}/.config/launcher/config.json"
    [calendar.config.json]="${HOME}/.config/calendar/config.json"
  )

  local tmpl dest rendered
  for tmpl dest in ${(kv)outs}; do
    [[ -f "${TEMPLATES_DIR}/${tmpl}" ]] || theme_die "missing template: ${tmpl}"
    rendered="$(theme_render "${TEMPLATES_DIR}/${tmpl}")"
    theme_write "${dest}" "${rendered}"
    theme_info "wrote ${dest}"
  done

  theme_emit_colors_env
  theme_info "wrote ${HOME}/.config/theme/colors.env"
  theme_info "active → ${name}"

  theme_set_wallpaper "${name}"
  theme_reload
  theme_info "reload hooks finished (new shells pick up cli.sh; Ghostty may need a reload)"
}

cmd="${1:-}"
case "${cmd}" in
  apply)
    shift
    theme_apply "${1:-}"
    ;;
  list)
    theme_list
    ;;
  current)
    theme_current
    ;;
  ""|-h|--help|help)
    print -r -- "usage: theme apply <palette> | theme list | theme current"
    ;;
  *)
    theme_die "unknown command '${cmd}' (apply|list|current)"
    ;;
esac
