# Generated by ./install.sh on 2026-10-06T12:23:33Z
# Re-run ./install.sh to change selections, or edit this file by hand.
{
  cli = {
    bat = true;
    btop = true;
    duti = true;
    eza = true;
    fd = true;
    fzf = true;
    gh = true;
    git = true;
    ncdu = true;
    ripgrep = true;
    starship = true;
    tldr = true;
    uv = true;
    zoxide = true;
    yazi = true;
  };

  rice = {
    omniwm = true;
    sketchybar = true;
    jankyborders = true;
    skhd = true;
    ghostty = true;
    stylix = true;
  };

  apps = {
    cursor = false;
    sublimeText = true;
    teamviewer = false;
    transmission = true;
    iina = true;
    libreoffice = false;
    geForceNow = false;
  };
}
