# Feature flag helpers shared by install.sh.
# Sourced; do not execute directly.

# Defaults when a host has no features.conf yet.
features_set_defaults() {
  CLI_bat=true
  CLI_btop=true
  CLI_duti=true
  CLI_eza=true
  CLI_fd=true
  CLI_fzf=true
  CLI_gh=true
  CLI_git=true
  CLI_ncdu=true
  CLI_ripgrep=true
  CLI_starship=true
  CLI_tldr=true
  CLI_uv=true
  CLI_zoxide=true
  CLI_yazi=true

  RICE_omniwm=true
  RICE_sketchybar=true
  RICE_jankyborders=true
  RICE_skhd=true
  RICE_ghostty=true

  APPS_cursor=true
  APPS_sublimeText=true
  APPS_teamviewer=false
  APPS_transmission=true
  APPS_iina=true
  APPS_libreoffice=true
  APPS_geForceNow=false
}

# Load KEY=value pairs from a features.conf (safe: only known keys).
features_load() {
  local file="$1"
  features_set_defaults
  [[ -f "$file" ]] || return 0

  local line key val
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    case "$key" in
      CLI_bat|CLI_btop|CLI_duti|CLI_eza|CLI_fd|CLI_fzf|CLI_gh|CLI_git|CLI_ncdu|CLI_ripgrep|CLI_starship|CLI_tldr|CLI_uv|CLI_zoxide|CLI_yazi|\
      RICE_omniwm|RICE_sketchybar|RICE_jankyborders|RICE_skhd|RICE_ghostty|\
      APPS_cursor|APPS_sublimeText|APPS_teamviewer|APPS_transmission|APPS_iina|APPS_libreoffice|APPS_geForceNow)
        eval "$key=$([[ "$val" == "true" ]] && echo true || echo false)"
        ;;
    esac
  done <"$file"
}

features_write() {
  local file="$1"
  mkdir -p "$(dirname "$file")"
  cat >"$file" <<EOF
# Generated by ./install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Re-run ./install.sh to change selections, or edit this file by hand.
CLI_bat=${CLI_bat}
CLI_btop=${CLI_btop}
CLI_duti=${CLI_duti}
CLI_eza=${CLI_eza}
CLI_fd=${CLI_fd}
CLI_fzf=${CLI_fzf}
CLI_gh=${CLI_gh}
CLI_git=${CLI_git}
CLI_ncdu=${CLI_ncdu}
CLI_ripgrep=${CLI_ripgrep}
CLI_starship=${CLI_starship}
CLI_tldr=${CLI_tldr}
CLI_uv=${CLI_uv}
CLI_zoxide=${CLI_zoxide}
CLI_yazi=${CLI_yazi}
RICE_omniwm=${RICE_omniwm}
RICE_sketchybar=${RICE_sketchybar}
RICE_jankyborders=${RICE_jankyborders}
RICE_skhd=${RICE_skhd}
RICE_ghostty=${RICE_ghostty}
APPS_cursor=${APPS_cursor}
APPS_sublimeText=${APPS_sublimeText}
APPS_teamviewer=${APPS_teamviewer}
APPS_transmission=${APPS_transmission}
APPS_iina=${APPS_iina}
APPS_libreoffice=${APPS_libreoffice}
APPS_geForceNow=${APPS_geForceNow}
EOF
}

# Echo brew formulae / casks / stow package names based on current flags.
features_brew_formulae() {
  local -a out=()
  out+=(stow gum jq)
  out+=(zsh-autosuggestions zsh-syntax-highlighting zsh-completions)
  $CLI_bat && out+=(bat)
  $CLI_btop && out+=(btop)
  $CLI_duti && out+=(duti)
  $CLI_eza && out+=(eza)
  $CLI_fd && out+=(fd)
  $CLI_fzf && out+=(fzf)
  $CLI_gh && out+=(gh)
  $CLI_git && out+=(git)
  $CLI_ncdu && out+=(ncdu)
  $CLI_ripgrep && out+=(ripgrep)
  $CLI_starship && out+=(starship)
  $CLI_tldr && out+=(tldr)
  $CLI_uv && out+=(uv)
  $CLI_zoxide && out+=(zoxide)
  $CLI_yazi && out+=(yazi)
  $RICE_sketchybar && out+=(sketchybar)
  $RICE_jankyborders && out+=(borders)
  $RICE_skhd && out+=(skhd)
  print -r -- "${out[@]}"
}

features_brew_casks() {
  local -a out=()
  $RICE_ghostty && out+=(ghostty)
  $RICE_omniwm && out+=(omniwm)
  $APPS_cursor && out+=(cursor)
  $APPS_sublimeText && out+=(sublime-text)
  $APPS_teamviewer && out+=(teamviewer)
  $APPS_transmission && out+=(transmission)
  $APPS_iina && out+=(iina)
  $APPS_libreoffice && out+=(libreoffice)
  $APPS_geForceNow && out+=(nvidia-geforce-now)
  # Fonts (cask)
  out+=(
    font-jetbrains-mono-nerd-font
    font-fira-code-nerd-font
    font-hack-nerd-font
    font-symbols-only-nerd-font
  )
  $RICE_sketchybar && out+=(font-sketchybar-app-font)
  print -r -- "${out[@]}"
}

# Stow package names (directories under packages/) to link for current flags.
features_stow_packages() {
  local -a out=(zsh)
  $CLI_git && out+=(git)
  $CLI_bat && out+=(bat)
  $CLI_btop && out+=(btop)
  $CLI_gh && out+=(gh)
  $CLI_starship && out+=(starship)
  $CLI_yazi && out+=(yazi)
  $RICE_ghostty && out+=(ghostty)
  $RICE_omniwm && out+=(omniwm)
  $RICE_skhd && out+=(skhd)
  $RICE_jankyborders && out+=(borders)
  $RICE_sketchybar && out+=(sketchybar)
  print -r -- "${out[@]}"
}
