# Feature flags for this host.
# Regenerated by ./install.sh — edit by hand or re-run the installer.
{
  cli = {
    bat = true;
    btop = true;
    duti = true;
    eza = true;
    fd = true;
    fzf = true;
    gh = true;
    git = true;
    ncdu = true;
    ripgrep = true;
    starship = true;
    tldr = true;
    uv = true;
    zoxide = true;
    yazi = true;
  };

  rice = {
    omniwm = true;
    sketchybar = true;
    jankyborders = true;
    skhd = true;
    ghostty = true;
    stylix = true;
  };

  apps = {
    cursor = true;
    sublimeText = true;
    teamviewer = false;
    transmission = true;
    iina = true;
    libreoffice = true;
    geForceNow = false;
  };
}
